/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardRulesRouteImport } from './routes/dashboard.rules'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardMapRouteImport } from './routes/dashboard.map'
import { Route as DashboardLicenseRouteImport } from './routes/dashboard.license'
import { Route as DashboardFuelRouteImport } from './routes/dashboard.fuel'
import { Route as DashboardEmergencyRouteImport } from './routes/dashboard.emergency'
import { Route as DashboardChatbotRouteImport } from './routes/dashboard.chatbot'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardAccidentRouteImport } from './routes/dashboard.accident'
import { Route as DashboardProfileIndexRouteImport } from './routes/dashboard.profile.index'
import { Route as DashboardProfileEditRouteImport } from './routes/dashboard.profile.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRulesRoute = DashboardRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMapRoute = DashboardMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLicenseRoute = DashboardLicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFuelRoute = DashboardFuelRouteImport.update({
  id: '/fuel',
  path: '/fuel',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmergencyRoute = DashboardEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatbotRoute = DashboardChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccidentRoute = DashboardAccidentRouteImport.update({
  id: '/accident',
  path: '/accident',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileIndexRoute = DashboardProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileEditRoute = DashboardProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/accident': typeof DashboardAccidentRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/chatbot': typeof DashboardChatbotRoute
  '/dashboard/emergency': typeof DashboardEmergencyRoute
  '/dashboard/fuel': typeof DashboardFuelRoute
  '/dashboard/license': typeof DashboardLicenseRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/rules': typeof DashboardRulesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/profile/edit': typeof DashboardProfileEditRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/accident': typeof DashboardAccidentRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/chatbot': typeof DashboardChatbotRoute
  '/dashboard/emergency': typeof DashboardEmergencyRoute
  '/dashboard/fuel': typeof DashboardFuelRoute
  '/dashboard/license': typeof DashboardLicenseRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/rules': typeof DashboardRulesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/profile/edit': typeof DashboardProfileEditRoute
  '/dashboard/profile': typeof DashboardProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/accident': typeof DashboardAccidentRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/chatbot': typeof DashboardChatbotRoute
  '/dashboard/emergency': typeof DashboardEmergencyRoute
  '/dashboard/fuel': typeof DashboardFuelRoute
  '/dashboard/license': typeof DashboardLicenseRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/rules': typeof DashboardRulesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/profile/edit': typeof DashboardProfileEditRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard/accident'
    | '/dashboard/analytics'
    | '/dashboard/chatbot'
    | '/dashboard/emergency'
    | '/dashboard/fuel'
    | '/dashboard/license'
    | '/dashboard/map'
    | '/dashboard/notifications'
    | '/dashboard/rules'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/profile/edit'
    | '/dashboard/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard/accident'
    | '/dashboard/analytics'
    | '/dashboard/chatbot'
    | '/dashboard/emergency'
    | '/dashboard/fuel'
    | '/dashboard/license'
    | '/dashboard/map'
    | '/dashboard/notifications'
    | '/dashboard/rules'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/profile/edit'
    | '/dashboard/profile'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard/accident'
    | '/dashboard/analytics'
    | '/dashboard/chatbot'
    | '/dashboard/emergency'
    | '/dashboard/fuel'
    | '/dashboard/license'
    | '/dashboard/map'
    | '/dashboard/notifications'
    | '/dashboard/rules'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/profile/edit'
    | '/dashboard/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rules': {
      id: '/dashboard/rules'
      path: '/rules'
      fullPath: '/dashboard/rules'
      preLoaderRoute: typeof DashboardRulesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/map': {
      id: '/dashboard/map'
      path: '/map'
      fullPath: '/dashboard/map'
      preLoaderRoute: typeof DashboardMapRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/license': {
      id: '/dashboard/license'
      path: '/license'
      fullPath: '/dashboard/license'
      preLoaderRoute: typeof DashboardLicenseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/fuel': {
      id: '/dashboard/fuel'
      path: '/fuel'
      fullPath: '/dashboard/fuel'
      preLoaderRoute: typeof DashboardFuelRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/emergency': {
      id: '/dashboard/emergency'
      path: '/emergency'
      fullPath: '/dashboard/emergency'
      preLoaderRoute: typeof DashboardEmergencyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chatbot': {
      id: '/dashboard/chatbot'
      path: '/chatbot'
      fullPath: '/dashboard/chatbot'
      preLoaderRoute: typeof DashboardChatbotRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/accident': {
      id: '/dashboard/accident'
      path: '/accident'
      fullPath: '/dashboard/accident'
      preLoaderRoute: typeof DashboardAccidentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile/': {
      id: '/dashboard/profile/'
      path: '/profile'
      fullPath: '/dashboard/profile/'
      preLoaderRoute: typeof DashboardProfileIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile/edit': {
      id: '/dashboard/profile/edit'
      path: '/profile/edit'
      fullPath: '/dashboard/profile/edit'
      preLoaderRoute: typeof DashboardProfileEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccidentRoute: typeof DashboardAccidentRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardChatbotRoute: typeof DashboardChatbotRoute
  DashboardEmergencyRoute: typeof DashboardEmergencyRoute
  DashboardFuelRoute: typeof DashboardFuelRoute
  DashboardLicenseRoute: typeof DashboardLicenseRoute
  DashboardMapRoute: typeof DashboardMapRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardRulesRoute: typeof DashboardRulesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProfileEditRoute: typeof DashboardProfileEditRoute
  DashboardProfileIndexRoute: typeof DashboardProfileIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccidentRoute: DashboardAccidentRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardChatbotRoute: DashboardChatbotRoute,
  DashboardEmergencyRoute: DashboardEmergencyRoute,
  DashboardFuelRoute: DashboardFuelRoute,
  DashboardLicenseRoute: DashboardLicenseRoute,
  DashboardMapRoute: DashboardMapRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardRulesRoute: DashboardRulesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProfileEditRoute: DashboardProfileEditRoute,
  DashboardProfileIndexRoute: DashboardProfileIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
